# -*- coding: utf-8 -*-
"""lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bziNZO5UUjOMbj5ZtfIkoXN2Zo0knszt
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

def show_comparision(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))

#Original image
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('original Grayscale image')
  plt.axis('off')

  #3x3 Kernal
  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title('3x3 kernal')
  plt.axis('off')

  #5x5 kernal
  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title('5x5 Kernal')
  plt.axis('off')

  #7x7 kernal
  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title('7x7 Kernal')
  plt.axis('off')

  plt.show()

